### ISSUE TITLE
Building an ntuple from the simulation output (no reconstruction)

### ISSUE THREAD

**Issue by luisaleperez** [iLCSoft/LCTuple#1]
Dear all,

I am working in the simulation of machine induced backgrounds for ILD. I successfully simulated several bunch-crossings of pairs backgrounds. I want to evaluate the background hit rates on all the sub-detectors. I don't think then that I need to run the reconstruction, so I can directly build a n-tuple with the required information using the output of the simulation (ddsim). For this I did as follows,

Marlin  lctuple_simhits_GuineaPig.xml --global.GearXMLFile=./gear_dd4hep.xml

where gear_dd4hep.xml is gear file of the geometry model, and lctuple_simhits_GuineaPig.xml the steering file to produce the n-tuple that you can visualize here below,
[lctuple_simhits_GuineaPig.xml.txt](https://github.com/iLCSoft/LCTuple/files/944308/lctuple_simhits_GuineaPig.xml.txt)

I am trying to put together different hit collections,

SimTrkHits:
    VXDCollection
     ETDCollection
     FTD_PIXELCollection
     FTD_STRIPCollection
     SETCollection
     SITCollection
     TPCCollection

and 

SimCaloHits: 
    MuonBarrelCollection
     MuonEndCapCollection
     EcalBarrelSiliconCollection
     EcalBarrelSiliconPreShowerCollection
     EcalEndcapSiliconCollection
     EcalEndcapSiliconPreShowerCollection
     EcalEndcapRingCollection
     EcalEndcapRingPreShowerCollection
     HcalBarrelRegCollection
     HcalEndCapRingsCollection
     HcalEndCapsCollection
     LHcalCollection
     LumiCalCollection
     BeamCalCollection

I am giving different indexes, through the <parameter name="InputCollectionIDs" type="IntVec"> parameter to these hits collections in order to identify then later in the ntuple with the different values of the stori variable. 

You can see the log file of one of my jobs for the n-tuple production here below,
[log_ntuple.log.txt](https://github.com/iLCSoft/LCTuple/files/944337/log_ntuple.log.txt)

For sure I am doing something wrong, because the when I look inside the n-tuple the variable stori has always the value 0. 

Can someone help me out here?

Many thanks,

  Alejandro

**Comment by luisaleperez** [comment]
Anyone with some comment?

**Comment by rete** [comment]
This is an old opened issue. Is it fixed ? Can you close it if so ?
