### ISSUE TITLE
Can we add all indepentent particles' information in isolep collections?

### ISSUE THREAD

**Issue by YancyW** [iLCSoft/LCTuple#6]
Currently, in the isolep collection (src/IsoLepBranches.cc), the output value in the root file can only be used for the process, which only has a single lepton. If there are two or more leptons in the input IsoLep collections, the results are meaningless. Because the output is just a float value, which equals to the sum of all those leptons. 
For example, the output value "IsoEvis" = the sum of all input lepton's energy. 

With this kind of output, users can't get exact information for each individual leptons. 
And in all other collection, like the jet, for each observable, the output is always an array, which always gives all individual information of every jets. 

So is it possible to update this isolep collection part to contain a vector for each observables and store all individual leptons' information?

**Comment by rete** [comment]
Hi Yancy,
why don't you make a pull request ? 
Have a look to our contribution guideline here: https://github.com/iLCSoft/ilcsoftDoc/blob/master/.github/CONTRIBUTING.md
Cheers

**Comment by rete** [comment]
@YancyW Should I close this ?

**Comment by beyerja** [comment]
@rete I don't think it's fixed.

**Comment by rete** [comment]
It's not "fixed". @YancyW was suggesting improvement in LCTuple

**Comment by YancyW** [comment]
OK. Please close this. Because I don't use LCTuple in my analysis, I don't have proper code to test that if I make some updates.

**Comment by rete** [comment]
Feel free to re-open it or make a pull request to change something in LCTuple.
Cheers, Remi
