### ISSUE TITLE
Add branch for hit time to tracker

### ISSUE THREAD

**Issue by gianelle** [iLCSoft/LCTuple#8]
Hi, 
I think that this is only an oversight, can you add the following line:

tree->Branch( (pre+"thtim").c_str() , _thtim , (pre+"thtim["+pre+"ntrh]/F").c_str() ) ;

to src/TrackerHitBranches.cc file?

thx, 
Ale

**Comment by petricm** [comment]
just do a PR

**Comment by gianelle** [comment]
Done:
https://github.com/iLCSoft/LCTuple/pull/9
